#!/usr/bin/perl

print "// This file was automatically generated by make_coresrv_syms.pl\n";
print ".section .text\n";

open(my $map, "<", "coresrv.map")
    or die "cannot poen coresrv.map";
while (<$map>) {
    if (/^\s+(0x\S+)\s+(__IDE__\S+)/) {
        print "\n";
        print ".global $2\n";
        print ".set $2, $1\n";
    }
}
