#!/bin/bash

echo "        // this file was automatically generated by make_core_idc.sh"
echo "        .section .idc_table"
find . -name "*\.c" -exec grep " _idc_" {} \; | perl -ne '/\s(_idc_[^\(]+)/; print "$1\n";' | sort | uniq | perl -ne '/_(.*)/; print "\n        .global $1\n$1:\n        calll _$1\n        pop %edx\n        int \$83\n";'
echo ""
echo "        .balignl 4096, 0x53cd5a90"
