        // this file was automatically generated by make_coresrv_idc.sh

int __IDC__coresrv_kbd_getc(IDC_PTR);
typedef uintptr_t coresrv_kbd_getc_ptr;

int __IDC__coresrv_rootfs_close(IDC_PTR, vfo_t* vto);
typedef uintptr_t coresrv_rootfs_close_ptr;

int __IDC__coresrv_rootfs_open(IDC_PTR, vfo_t* vfo, const char *name, int flags);
typedef uintptr_t coresrv_rootfs_open_ptr;

int __IDC__coresrv_vfs_close(IDC_PTR, vfo_t*);
typedef uintptr_t coresrv_vfs_close_ptr;

int __IDC__coresrv_vfs_fsync(IDC_PTR, vfo_t*);
typedef uintptr_t coresrv_vfs_fsync_ptr;

int __IDC__coresrv_vfs_ftruncate(IDC_PTR, vfo_t*, off_t);
typedef uintptr_t coresrv_vfs_ftruncate_ptr;

int __IDC__coresrv_vfs_open(IDC_PTR, vfo_t*, const char *name, int flags);
typedef uintptr_t coresrv_vfs_open_ptr;

off_t __IDC__coresrv_rootfs_lseek(IDC_PTR, vfo_t* vto, off_t off, int where);
typedef uintptr_t coresrv_rootfs_lseek_ptr;

off_t __IDC__coresrv_vfs_lseek(IDC_PTR, vfo_t*, off_t, int);
typedef uintptr_t coresrv_vfs_lseek_ptr;

ssize_t __IDC__coresrv_rootfs_read(IDC_PTR, vfo_t* vto, void * buf, size_t size);
typedef uintptr_t coresrv_rootfs_read_ptr;

ssize_t __IDC__coresrv_vfs_read(IDC_PTR, vfo_t*, void *, size_t);
typedef uintptr_t coresrv_vfs_read_ptr;

ssize_t __IDC__coresrv_vfs_write(IDC_PTR, vfo_t*, const void *, size_t);
typedef uintptr_t coresrv_vfs_write_ptr;

unsigned __IDC__coresrv_rtc_ticks(IDC_PTR);
typedef uintptr_t coresrv_rtc_ticks_ptr;

void __IDC__coresrv_rtc_beep(IDC_PTR, unsigned freq, unsigned ticks);
typedef uintptr_t coresrv_rtc_beep_ptr;

void __IDC__coresrv_vga_putc(IDC_PTR, unsigned x, unsigned y, unsigned cursorx, unsigned c, unsigned color);
typedef uintptr_t coresrv_vga_putc_ptr;

extern uintptr_t __IDE__coresrv_kbd_getc;
extern uintptr_t __IDE__coresrv_rootfs_close;
extern uintptr_t __IDE__coresrv_rootfs_lseek;
extern uintptr_t __IDE__coresrv_rootfs_open;
extern uintptr_t __IDE__coresrv_rootfs_read;
extern uintptr_t __IDE__coresrv_rtc_beep;
extern uintptr_t __IDE__coresrv_rtc_ticks;
extern uintptr_t __IDE__coresrv_vfs_open;
extern uintptr_t __IDE__coresrv_vga_putc;
