#ifndef __HELLBENDER_KERNEL_SIZES_H__
#define __HELLBENDER_KERNEL_SIZES_H__

#define CACHE_LINE 64
#define PAGE_SIZE 4096
#define TABLE_SIZE (512*PAGE_SIZE)
#define TABLEDIR_SIZE (512*TABLE_SIZE)

#endif
