#define sizeof_thread_context 48
#define sizeof_thread_registers 128
#define offsetof_thread_registers_rax 0
#define sizeof_thread_registers_rax 8
#define offsetof_thread_registers_rbx 8
#define sizeof_thread_registers_rbx 8
#define offsetof_thread_registers_rcx 16
#define sizeof_thread_registers_rcx 8
#define offsetof_thread_registers_rdx 24
#define sizeof_thread_registers_rdx 8
#define offsetof_thread_registers_rbp 32
#define sizeof_thread_registers_rbp 8
#define offsetof_thread_registers_rsi 40
#define sizeof_thread_registers_rsi 8
#define offsetof_thread_registers_rdi 48
#define sizeof_thread_registers_rdi 8
#define offsetof_thread_registers_r8 56
#define sizeof_thread_registers_r8 8
#define offsetof_thread_registers_r9 64
#define sizeof_thread_registers_r9 8
#define offsetof_thread_registers_r10 72
#define sizeof_thread_registers_r10 8
#define offsetof_thread_registers_r11 80
#define sizeof_thread_registers_r11 8
#define offsetof_thread_registers_r12 88
#define sizeof_thread_registers_r12 8
#define offsetof_thread_registers_r13 96
#define sizeof_thread_registers_r13 8
#define offsetof_thread_registers_r14 104
#define sizeof_thread_registers_r14 8
#define offsetof_thread_registers_r15 112
#define sizeof_thread_registers_r15 8
#define sizeof_thread_state 176
#define offsetof_thread_state_context 128
#define sizeof_thread_state_context 48
#define offsetof_thread_state_registers 0
#define sizeof_thread_state_registers 128
#define sizeof_cpu 4096
#define offsetof_cpu_nested_isr 0
#define sizeof_cpu_nested_isr 8
#define offsetof_cpu_kernel_stack_top 8
#define sizeof_cpu_kernel_stack_top 8
#define offsetof_cpu_current_thread 24
#define sizeof_cpu_current_thread 8
#define offsetof_cpu_current_thread_rsp 32
#define sizeof_cpu_current_thread_rsp 8
