// Automatically generated by make_syscall_size.pl
#include <kernel/syscall.h>

struct __attribute__((__packed__)) {
  const char* str;
  size_t n;
} _syscall_print__size;

struct __attribute__((__packed__)) {
  void* set_or_null;
  intptr_t delta_or_zero;
} _syscall_set_program_break__size;

struct __attribute__((__packed__)) {
  void* address;
  unsigned size;
} _syscall_make_readonly__size;

struct __attribute__((__packed__)) {
  void* address;
  unsigned size;
} _syscall_make_executable__size;

struct __attribute__((__packed__)) {
  int status;
} _syscall_exit__size;

struct __attribute__((__packed__)) {
  const char *path;
  char *const* argv;
  char *const* envp;
} _syscall_spawn__size;

struct __attribute__((__packed__)) {
  char* path;
} _syscall_current_exec_path__size;

struct __attribute__((__packed__)) {
  int *argc;
  int *envc;
  char** strings;
} _syscall_get_environment__size;

struct __attribute__((__packed__)) {
} _syscall_yield__size;

struct __attribute__((__packed__)) {
  volatile unsigned *obj;
  unsigned value;
} _syscall_wait_eq__size;

struct __attribute__((__packed__)) {
  volatile unsigned *obj;
  unsigned value;
} _syscall_wait_neq__size;

struct __attribute__((__packed__)) {
  volatile unsigned *obj;
} _syscall_notify__size;

void main() {}
