        // this file was automatically generated by make_coresrv_idc.sh

int __IDC__coresrv_kbd_getc(IDC_PTR);
extern uintptr_t __IDE__coresrv_kbd_getc;
typedef uintptr_t coresrv_kbd_getc_ptr;

int __IDC__coresrv_vfs_close(IDC_PTR, vfo_t*);
extern uintptr_t __IDE__coresrv_vfs_close;
typedef uintptr_t coresrv_vfs_close_ptr;

int __IDC__coresrv_vfs_fsync(IDC_PTR, vfo_t*);
extern uintptr_t __IDE__coresrv_vfs_fsync;
typedef uintptr_t coresrv_vfs_fsync_ptr;

int __IDC__coresrv_vfs_ftruncate(IDC_PTR, vfo_t*, off_t);
extern uintptr_t __IDE__coresrv_vfs_ftruncate;
typedef uintptr_t coresrv_vfs_ftruncate_ptr;

int __IDC__coresrv_vfs_open(IDC_PTR, vfo_t*, const char *name, int flags);
extern uintptr_t __IDE__coresrv_vfs_open;
typedef uintptr_t coresrv_vfs_open_ptr;

off_t __IDC__coresrv_vfs_lseek(IDC_PTR, vfo_t*, off_t, int);
extern uintptr_t __IDE__coresrv_vfs_lseek;
typedef uintptr_t coresrv_vfs_lseek_ptr;

ssize_t __IDC__coresrv_vfs_read(IDC_PTR, vfo_t*, void *, size_t);
extern uintptr_t __IDE__coresrv_vfs_read;
typedef uintptr_t coresrv_vfs_read_ptr;

ssize_t __IDC__coresrv_vfs_write(IDC_PTR, vfo_t*, const void *, size_t);
extern uintptr_t __IDE__coresrv_vfs_write;
typedef uintptr_t coresrv_vfs_write_ptr;

unsigned __IDC__coresrv_rtc_ticks(IDC_PTR);
extern uintptr_t __IDE__coresrv_rtc_ticks;
typedef uintptr_t coresrv_rtc_ticks_ptr;

void __IDC__coresrv_rtc_beep(IDC_PTR, unsigned freq, unsigned ticks);
extern uintptr_t __IDE__coresrv_rtc_beep;
typedef uintptr_t coresrv_rtc_beep_ptr;
